"""Convert the three Paycom config files into a single Python data module
(apps/paycom/withholding_data.py) so the runtime never has to read them off
disk. Run once; commit the generated module; delete the originals from the
deploy path. Re-run any time the source files change."""

import os, re, pprint, yaml
import pandas as pd

SRC_DIR = r"C:\Users\rohit.kaushik\Downloads\Unified Audit Tool\Paycom to UZIO withholding"
OUT_PATH = r"C:\Users\rohit.kaushik\Downloads\Unified_Audit_Tool\apps\paycom\withholding_data.py"


def load_mapping_rows() -> list:
    """Read Mapping.xlsx and return only rows that have a real Uzio Field Key."""
    df = pd.read_excel(os.path.join(SRC_DIR, "Mapping.xlsx"), dtype=str)
    df = df.fillna("")
    rows = []
    for _, r in df.iterrows():
        uz = str(r.get("Uzio Field Key", "")).strip()
        pc = str(r.get("PayCom Column", "")).strip()
        cm = str(r.get("Comments", "")).strip()
        if not uz or uz.lower() == "nan" or not pc or pc.lower() == "nan":
            continue
        rows.append({
            "Uzio Field Key": uz,
            "PayCom Column": pc,
            "Comments": "" if cm.lower() == "nan" else cm,
        })
    return rows


def load_filing_status_map() -> dict:
    """Parse filing status_code.txt using the same regex Paycom uses."""
    with open(os.path.join(SRC_DIR, "filing status_code.txt"), "r", encoding="utf-8", errors="ignore") as f:
        text = f.read()
    text = re.sub(r"//.*", "", text)  # strip Java line comments
    pattern = re.compile(r'([A-Z][A-Z0-9_]+)\("([^"]+)"\)')
    return dict(pattern.findall(text))


def load_labels_by_state() -> dict:
    """Read key_mapping.yml into a nested {state: {field_key: label}} dict."""
    with open(os.path.join(SRC_DIR, "key_mapping.yml"), "r", encoding="utf-8") as f:
        raw = yaml.safe_load(f)
    out = {}
    for st, st_map in raw.get("withholding_es", {}).get("mappings", {}).items():
        if not isinstance(st_map, dict):
            continue
        bucket = {}
        for k, v in st_map.items():
            if isinstance(v, dict) and "label" in v:
                bucket[k] = str(v["label"])
            elif isinstance(v, str):
                bucket[k] = v
        out[str(st).upper()] = bucket
    return out


def emit_module(mappings, filing_map, labels) -> str:
    lines = []
    lines.append('"""')
    lines.append("Inlined withholding config for the Paycom audit tool.")
    lines.append("")
    lines.append("Generated by scratch/generate_paycom_data_module.py from:")
    lines.append("  - Mapping.xlsx            (Paycom -> UZIO field mapping)")
    lines.append("  - filing status_code.txt  (UZIO filing-status enum -> ADP/Paycom label)")
    lines.append("  - key_mapping.yml         (field labels per jurisdiction)")
    lines.append("")
    lines.append("To regenerate after the source files change, run that script.")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")

    # MAPPING_ROWS
    lines.append("# Paycom -> UZIO field mapping (was Mapping.xlsx).")
    lines.append("# Only rows with a populated 'Uzio Field Key' are included.")
    lines.append(f"MAPPING_ROWS: list[dict] = {pprint.pformat(mappings, sort_dicts=False, width=120)}")
    lines.append("")

    # FILING_STATUS_MAP
    lines.append("# UZIO filing-status enum -> human-readable label (was filing status_code.txt).")
    sorted_fs = dict(sorted(filing_map.items()))
    lines.append(f"FILING_STATUS_MAP: dict[str, str] = {pprint.pformat(sorted_fs, sort_dicts=False, width=100)}")
    lines.append("")

    # LABELS_BY_STATE — large; emit jurisdiction by jurisdiction for readability
    lines.append("# Field display labels per jurisdiction (was key_mapping.yml).")
    lines.append("# Structure: {jurisdiction_code: {field_key: display_label}}")
    lines.append("LABELS_BY_STATE: dict[str, dict[str, str]] = {")
    for st in sorted(labels.keys()):
        st_bucket = labels[st]
        if not st_bucket:
            lines.append(f"    {st!r}: {{}},")
            continue
        lines.append(f"    {st!r}: {{")
        for k, v in st_bucket.items():
            lines.append(f"        {k!r}: {v!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    print("Reading Mapping.xlsx...")
    mappings = load_mapping_rows()
    print(f"  {len(mappings)} active mapping rows")
    for m in mappings:
        print(f"    {m['Uzio Field Key']:40s} <- {m['PayCom Column']}")
    print()

    print("Reading filing status_code.txt...")
    filing = load_filing_status_map()
    print(f"  {len(filing)} filing-status codes")
    print()

    print("Reading key_mapping.yml...")
    labels = load_labels_by_state()
    total = sum(len(v) for v in labels.values())
    print(f"  {len(labels)} jurisdictions, {total} labels total")
    print()

    src = emit_module(mappings, filing, labels)
    print(f"Writing {OUT_PATH}  ({len(src):,} chars, ~{src.count(chr(10)):,} lines)")
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(src)
    print("Done.")


if __name__ == "__main__":
    main()
